version: "3.9"

services:
  my-postgres:
    image: postgres:latest
    container_name: my-postgres
    hostname: postgres
    ports:
      - 65432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_PORT=5432
      - PGDATA=/data
    volumes:
      - ./containers/postgres:/data
    restart: unless-stopped

  my-api:
    build:
      dockerfile: Dockerfile
    container_name: my-api
    depends_on: [ my-postgres ]
    ports:
      - 8081:8081
    restart: unless-stopped
